// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually.


import type { Sync } from "@engine";

import * as sync_reviews from "./reviews.sync.ts";
import * as sync_sample from "./sample.sync.ts";
import * as sync_stores from "./stores.sync.ts";
import * as sync_tagging from "./tagging.sync.ts";
import * as sync_user_auth from "./user_auth.sync.ts";

const allSyncs: Record<string, Sync> = {};


for (const [name, func] of Object.entries(sync_reviews)) {
  if (typeof func === "function") {
    allSyncs[`reviews.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_sample)) {
  if (typeof func === "function") {
    allSyncs[`sample.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_stores)) {
  if (typeof func === "function") {
    allSyncs[`stores.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_tagging)) {
  if (typeof func === "function") {
    allSyncs[`tagging.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_user_auth)) {
  if (typeof func === "function") {
    allSyncs[`user_auth.${name}`] = func as Sync;
  }
}

export default allSyncs;
