// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { getDb } from "@utils/database.ts";

import LikertSurveyConcept from "./LikertSurvey/LikertSurveyConcept.ts";
import RatingConcept from "./Rating/RatingConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import ReviewConcept from "./Review/ReviewConcept.ts";
import StoreConcept from "./Store/StoreConcept.ts";
import TaggingConcept from "./Tagging/TaggingConcept.ts";
import UserConcept from "./User/UserConcept.ts";

export type { default as LikertSurveyConcept } from "./LikertSurvey/LikertSurveyConcept.ts";
export type { default as RatingConcept } from "./Rating/RatingConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as ReviewConcept } from "./Review/ReviewConcept.ts";
export type { default as StoreConcept } from "./Store/StoreConcept.ts";
export type { default as TaggingConcept } from "./Tagging/TaggingConcept.ts";
export type { default as UserConcept } from "./User/UserConcept.ts";

// Initialize the database connection
export const [db, client] = await getDb();

export const LikertSurvey = Engine.instrumentConcept(new LikertSurveyConcept(db));
export const Rating = Engine.instrumentConcept(new RatingConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const Review = Engine.instrumentConcept(new ReviewConcept(db));
export const Store = Engine.instrumentConcept(new StoreConcept(db));
export const Tagging = Engine.instrumentConcept(new TaggingConcept(db));
export const User = Engine.instrumentConcept(new UserConcept(db));
